name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint (if script exists)
        run: npm run lint --if-present

      - name: Test (if script exists)
        run: npm test --if-present -- --watchAll=false

      - name: Build
        run: npm run build